"""empty message

Revision ID: 448299250292
Revises: baff3169b46a
Create Date: 2024-12-10 16:10:35.972788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448299250292'
down_revision = 'baff3169b46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=200), nullable=False),
    sa.Column('search_type', sa.String(length=50), nullable=False),
    sa.Column('date_searched', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_history')
    # ### end Alembic commands ###
